name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shahedk/image-resizer:$(date +%s)

    - name: Login to Docker Hub
      run: docker login -u shahedk -p {{ $secrets.DOCKERHUB_PAT }}

    - name: Push to Docker Hub
      run: docker push shahedk/image-resizer:$(date +%s)

      
